spring:
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /

# --------------------------------------------- 配置mybatis ---------------------------------------------------- #
mybatis:
  mapper-locations: classpath:generator/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
