proxy:
  url: http://www.66ip.cn/nmtq.php?getnum=300&isp=0&anonymoustype=0&start=&ports=&export=&ipaddress=&area=0&proxytype=2&api=66ip
  cookie:
  checkUrl: http://www.baidu.com

spring:
  # ---------------------------------------------  数据库配置(默认使用mysql：5.5+) -----------------------------------#
  # ---------------------------------------------  allowMultiQueries=true 允许在sql中出现`;` -----------------------------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-nkp6kzna.sql.tencentcdb.com:21822/test?characterEncoding=utf-8&allowMultiQueries=true
    username: test
    password: test123@
    # 连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 60
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1


http:
  client:
    connection-request-timeout: 10000
    connect-timeout: 10000
    socket-timeout: 50000
